<svelte:head>
  <title>Getting Started - API Builder</title>
</svelte:head>

<div>
  <h1 class="text-ab-dark-blue mb-4 text-2xl font-bold">Getting Started</h1>

  <p class="text-ab-dark-blue mb-8 text-lg leading-relaxed">From zero to generated, compiled code in under a minute.</p>

  <!-- Step 0: Install -->
  <div class="mb-8">
    <h2 class="text-ab-blue mb-4 flex items-center gap-2 text-lg font-bold">
      <span class="inline-flex h-7 w-7 items-center justify-center rounded-full bg-gray-400 text-xs text-white">0</span>
      Install the CLI
    </h2>
    <div class="card">
      <p class="text-ab-dark-blue mb-3">
        The <code class="rounded bg-gray-100 px-1.5 py-0.5">api</code> CLI is a Ruby script with no gem dependencies — just clone and add to your
        PATH.
      </p>
      <pre class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code
          >git clone https://github.com/mbryzek/devops.git ~/apibuilder-cli
export PATH="$HOME/apibuilder-cli/bin:$PATH"</code
        ></pre>
      <p class="text-ab-gray mt-3 text-sm">
        Requires Ruby (any recent version). Add the <code class="rounded bg-gray-100 px-1.5 py-0.5">export</code> line to your shell profile to
        make it permanent.
      </p>
    </div>
  </div>

  <!-- Step 1: Initialize -->
  <div class="mb-8" id="quick-start">
    <h2 class="text-ab-blue mb-4 flex items-center gap-2 text-lg font-bold">
      <span class="bg-ab-blue inline-flex h-7 w-7 items-center justify-center rounded-full text-xs text-white">1</span>
      Initialize
    </h2>
    <div class="card">
      <p class="text-ab-dark-blue mb-3">
        Run <code class="rounded bg-gray-100 px-1.5 py-0.5">api init</code> from your project directory to create an anonymous org (a temporary
        workspace so you can try API Builder without creating an account) and set up your project config. No signup required.
      </p>
      <pre class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code
          >api init --language typescript              # TypeScript project
api init --language scala                   # Scala project
api init --language typescript --language scala  # both</code
        ></pre>
      <p class="text-ab-dark-blue mt-3 text-sm">
        This writes your credentials to <code class="rounded bg-gray-100 px-1.5 py-0.5">~/.apibuilder/config</code>
        and creates a <code class="rounded bg-gray-100 px-1.5 py-0.5">.api/config</code> in the current directory with default generators for
        your language. For a TypeScript project, the generated config looks like:
      </p>
      <pre class="mt-3 overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code
          >{@html `# .api/config (generated by api init)
&lt;your-org&gt;:
  - generators:
      typescript: ./src/generated
    applications:
      my-api:`}</code
        ></pre>
      <p class="text-ab-gray mt-3 text-sm">
        You only need to run <code class="rounded bg-gray-100 px-1.5 py-0.5">api init</code> once per machine. If you already have
        <code class="rounded bg-gray-100 px-1.5 py-0.5">~/.apibuilder/config</code>, skip this step.
      </p>
    </div>
  </div>

  <!-- Step 2: Write a Spec -->
  <div class="mb-8">
    <h2 class="text-ab-blue mb-4 flex items-center gap-2 text-lg font-bold">
      <span class="bg-ab-blue inline-flex h-7 w-7 items-center justify-center rounded-full text-xs text-white">2</span>
      Write a Spec
    </h2>
    <div class="card">
      <p class="text-ab-dark-blue mb-3">
        Create <code class="rounded bg-gray-100 px-1.5 py-0.5 text-sm">spec/my-api.json</code> with your API definition. The file name
        determines the application name — <code class="rounded bg-gray-100 px-1.5 py-0.5">spec/my-api.json</code>
        maps to the <code class="rounded bg-gray-100 px-1.5 py-0.5">my-api</code> application in your config. See the
        <a href="/doc/apiJson" class="text-ab-blue hover:text-ab-dark-blue underline">api.json reference</a> for the full format.
      </p>
      <pre class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code
          >{@html `{
  "name": "my-api",
  "namespace": "com.example.api.v0",
  "models": {
    "user": {
      "fields": [
        { "name": "id", "type": "string" },
        { "name": "email", "type": "string" }
      ]
    }
  },
  "resources": {
    "user": {
      "operations": [
        {
          "method": "GET",
          "path": "/users/:id",
          "responses": { "200": { "type": "user" } }
        }
      ]
    }
  }
}`}</code
        ></pre>
      <p class="text-ab-gray mt-3 text-sm">
        The <code class="rounded bg-gray-100 px-1.5 py-0.5">namespace</code> becomes the package name in generated code (e.g.
        <code class="rounded bg-gray-100 px-1.5 py-0.5">com.example.api.v0</code> in Scala, or the module path in TypeScript).
      </p>
    </div>
  </div>

  <!-- Step 3: Generate Code -->
  <div class="mb-8">
    <h2 class="text-ab-blue mb-4 flex items-center gap-2 text-lg font-bold">
      <span class="bg-ab-blue inline-flex h-7 w-7 items-center justify-center rounded-full text-xs text-white">3</span>
      Generate Code
    </h2>
    <div class="card">
      <p class="text-ab-dark-blue mb-3">Upload your spec and generate code in one step:</p>
      <pre class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code>api</code></pre>
      <p class="text-ab-dark-blue mt-3 text-sm">
        This reads your <code class="rounded bg-gray-100 px-1.5 py-0.5">.api/config</code>, validates and uploads each spec, then runs the
        configured code generators. You should see output like:
      </p>
      <pre class="mt-3 overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm text-gray-600"><code
          >{@html `==> Auto-detected operations: upload, codegen
==> Processing 1 organization
==> Submitting batch (1 application, operations: upload, codegen)
==> Batch completed
==> Downloading generated code...
==> Extracting files...
  wrote ./src/generated/my-api.ts
  1 written, 0 unchanged
==> Done (2.1 seconds)`}</code
        ></pre>
      <p class="text-ab-dark-blue mt-3 text-sm">
        If nothing is generated, make sure your spec defines at least one resource — code generators produce output from resources and their
        operations. See <a href="/doc/generators" class="text-ab-blue hover:text-ab-dark-blue underline">available generators</a> for the full
        list.
      </p>
      <p class="text-ab-gray mt-2 text-sm">
        You can also validate a spec without generating code: <code class="rounded bg-gray-100 px-1.5 py-0.5"
          >api validate spec/my-api.json</code
        >
      </p>
    </div>
  </div>

  <!-- Step 4: Compile -->
  <div class="mb-8">
    <h2 class="text-ab-blue mb-4 flex items-center gap-2 text-lg font-bold">
      <span class="bg-ab-blue inline-flex h-7 w-7 items-center justify-center rounded-full text-xs text-white">4</span>
      Compile and Verify
    </h2>
    <div class="card">
      <p class="text-ab-dark-blue mb-3">
        Generated code creates type-safe contracts between your spec and your implementation. The compiler enforces that they stay in sync —
        if it compiles, your code matches the spec. If not, the compiler errors tell you exactly what to fix.
      </p>
      <pre class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code
          >sbt compile    # Scala
tsc --noEmit   # TypeScript</code
        ></pre>
    </div>
  </div>

  <!-- Step 5: Test -->
  <div class="mb-8">
    <h2 class="text-ab-blue mb-4 flex items-center gap-2 text-lg font-bold">
      <span class="bg-ab-blue inline-flex h-7 w-7 items-center justify-center rounded-full text-xs text-white">5</span>
      Write Tests
    </h2>
    <div class="card">
      <p class="text-ab-dark-blue mb-3">
        API Builder generates mock clients that implement the same interface as real clients but return test data without making HTTP calls.
        Override only what you need per test:
      </p>
      <pre class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code
          >{@html `// Scala example using generated mock client
val mock = new MockClient()
val user = mock.users.getById("test-id")
assert(user.id == "test-id")`}</code
        ></pre>
      <p class="text-ab-gray mt-3 text-sm">
        Mock clients are generated automatically when you include the
        <code class="rounded bg-gray-100 px-1.5 py-0.5">bryzek_play_mock_client</code> (Scala) generator in your
        <code class="rounded bg-gray-100 px-1.5 py-0.5">.api/config</code>.
      </p>
    </div>
  </div>

  <!-- Project Structure -->
  <div class="mb-8">
    <h2 class="text-ab-blue mb-4 flex items-center gap-2 text-lg font-bold">
      <span class="inline-flex h-7 w-7 items-center justify-center rounded-full bg-gray-400 text-xs text-white">&#10003;</span>
      What You End Up With
    </h2>
    <div class="card">
      <p class="text-ab-dark-blue mb-3">After completing these steps, your project structure looks like:</p>
      <pre class="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-4 text-sm"><code
          >{@html `my-project/
  .api/
    config                # generator config (created by api init)
  spec/
    my-api.json           # your API spec
  src/
    generated/
      my-api.ts           # generated client code (don't edit)
    index.ts              # your implementation`}</code
        ></pre>
      <p class="text-ab-gray mt-3 text-sm">
        Files in <code class="rounded bg-gray-100 px-1.5 py-0.5">src/generated/</code> are overwritten each time you run
        <code class="rounded bg-gray-100 px-1.5 py-0.5">api</code> — commit them to source control but don't edit them by hand.
      </p>
    </div>
  </div>

  <!-- Agent Skill -->
  <div class="mb-8">
    <details>
      <summary class="text-ab-blue mb-4 flex cursor-pointer items-center gap-2 text-lg font-bold">
        <span class="bg-ab-blue inline-flex h-7 w-7 items-center justify-center rounded-full text-xs text-white">&#10022;</span>
        For AI Agents
      </summary>
      <div class="card mt-4">
        <p class="text-ab-dark-blue mb-3">
          Give your AI agent the full API Builder workflow as a skill. The skill teaches the agent spec authoring, validation, code
          generation, compiler verification, and testing.
        </p>
        <p class="text-ab-dark-blue">
          <a
            href="https://github.com/mbryzek/apibuilder-ui/blob/main/skills/apibuilder.md"
            class="text-ab-blue hover:text-ab-dark-blue underline"
          >
            View the skill on GitHub
          </a>
        </p>
      </div>
    </details>
  </div>

  <!-- CTA -->
  <div class="mt-12 mb-8 text-center">
    <p class="text-ab-dark-blue mb-4">Explore the full API specification format.</p>
    <a href="/doc/apiJson" class="btn-primary inline-block">api.json Reference</a>
  </div>
</div>
