<svelte:head>
	<title>Getting Started - API Builder</title>
</svelte:head>

<div>
	<h1 class="text-2xl font-bold text-ab-dark-blue mb-4">Getting Started</h1>

	<p class="text-ab-dark-blue mb-8 text-lg leading-relaxed">
		From zero to generated, compiled code in under a minute.
	</p>

	<!-- Step 1: Initialize -->
	<div class="mb-8" id="quick-start">
		<h2 class="text-lg font-bold text-ab-blue mb-4 flex items-center gap-2">
			<span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-ab-blue text-white text-xs">1</span>
			Initialize
		</h2>
		<div class="card">
			<p class="text-ab-dark-blue mb-3">
				Create an anonymous org, API token, and local project config. No signup required.
				Specify your language to set up default code generators.
			</p>
			<pre class="bg-gray-50 border border-gray-200 rounded-lg p-4 text-sm overflow-x-auto"><code>api init --language typescript              # TypeScript project
api init --language scala                   # Scala project
api init --language typescript --language scala  # both</code></pre>
			<p class="text-ab-dark-blue text-sm mt-3">
				This writes your credentials to <code class="bg-gray-100 px-1.5 py-0.5 rounded">~/.apibuilder/config</code>
				and creates a <code class="bg-gray-100 px-1.5 py-0.5 rounded">.api/config</code> in the current directory.
				For a TypeScript project, the generated config looks like:
			</p>
			<pre class="bg-gray-50 border border-gray-200 rounded-lg p-4 text-sm overflow-x-auto mt-3"><code>{@html `# .api/config (generated by api init)
&lt;your-org&gt;:
  - generators:
      typescript: ./src/generated
    applications:
      my-api:`}</code></pre>
			<p class="text-ab-gray text-sm mt-3">
				If you already have <code class="bg-gray-100 px-1.5 py-0.5 rounded">~/.apibuilder/config</code>,
				you can skip this step — you only need to run <code class="bg-gray-100 px-1.5 py-0.5 rounded">api init</code> once.
			</p>
		</div>
	</div>

	<!-- Step 2: Write a Spec -->
	<div class="mb-8">
		<h2 class="text-lg font-bold text-ab-blue mb-4 flex items-center gap-2">
			<span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-ab-blue text-white text-xs">2</span>
			Write a Spec
		</h2>
		<div class="card">
			<p class="text-ab-dark-blue mb-3">
				Create <code class="text-sm bg-gray-100 px-1.5 py-0.5 rounded">spec/my-api.json</code> with your API definition.
				The file name determines the application name — <code class="bg-gray-100 px-1.5 py-0.5 rounded">spec/my-api.json</code>
				maps to the <code class="bg-gray-100 px-1.5 py-0.5 rounded">my-api</code> application in your config.
				See the <a href="/doc/apiJson" class="text-ab-blue hover:text-ab-dark-blue underline">api.json reference</a> for the full format.
			</p>
			<pre class="bg-gray-50 border border-gray-200 rounded-lg p-4 text-sm overflow-x-auto"><code>{@html `{
  "name": "my-api",
  "namespace": "com.example.api.v0",
  "models": {
    "user": {
      "fields": [
        { "name": "id", "type": "string" },
        { "name": "email", "type": "string" }
      ]
    }
  },
  "resources": {
    "user": {
      "operations": [
        {
          "method": "GET",
          "path": "/users/:id",
          "responses": { "200": { "type": "user" } }
        }
      ]
    }
  }
}`}</code></pre>
		</div>
	</div>

	<!-- Step 3: Generate Code -->
	<div class="mb-8">
		<h2 class="text-lg font-bold text-ab-blue mb-4 flex items-center gap-2">
			<span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-ab-blue text-white text-xs">3</span>
			Generate Code
		</h2>
		<div class="card">
			<p class="text-ab-dark-blue mb-3">
				Upload your spec and generate code in one step:
			</p>
			<pre class="bg-gray-50 border border-gray-200 rounded-lg p-4 text-sm overflow-x-auto"><code>api</code></pre>
			<p class="text-ab-dark-blue text-sm mt-3">
				This reads your <code class="bg-gray-100 px-1.5 py-0.5 rounded">.api/config</code>, validates and uploads
				each spec, then runs the configured code generators. Output files are written to the directories
				specified in your config. See <a href="/doc/generators" class="text-ab-blue hover:text-ab-dark-blue underline">available generators</a>.
			</p>
			<p class="text-ab-dark-blue text-sm mt-3">
				If nothing is generated, make sure your spec defines at least one resource — code generators
				produce output from resources and their operations.
			</p>
			<p class="text-ab-gray text-sm mt-2">
				You can also validate a spec without generating code: <code class="bg-gray-100 px-1.5 py-0.5 rounded">api validate spec/my-api.json</code>
			</p>
		</div>
	</div>

	<!-- Step 4: Compile -->
	<div class="mb-8">
		<h2 class="text-lg font-bold text-ab-blue mb-4 flex items-center gap-2">
			<span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-ab-blue text-white text-xs">4</span>
			Compile and Verify
		</h2>
		<div class="card">
			<p class="text-ab-dark-blue mb-3">
				Compile the generated code alongside your implementation. If it compiles, your implementation
				matches the spec. If not, the compiler errors tell you exactly what to fix.
			</p>
			<pre class="bg-gray-50 border border-gray-200 rounded-lg p-4 text-sm overflow-x-auto"><code>sbt compile    # Scala
tsc --noEmit   # TypeScript</code></pre>
		</div>
	</div>

	<!-- Step 5: Test -->
	<div class="mb-8">
		<h2 class="text-lg font-bold text-ab-blue mb-4 flex items-center gap-2">
			<span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-ab-blue text-white text-xs">5</span>
			Write Tests
		</h2>
		<div class="card">
			<p class="text-ab-dark-blue">
				Use generated mock clients to test your implementation. They share the same interface
				as real clients — override only what you need per scenario.
			</p>
		</div>
	</div>

	<!-- Agent Skill -->
	<div class="mb-8">
		<h2 class="text-lg font-bold text-ab-blue mb-4 flex items-center gap-2">
			<span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-ab-blue text-white text-xs">&#10022;</span>
			Add the Skill to Your Agent
		</h2>
		<div class="card">
			<p class="text-ab-dark-blue mb-3">
				Give your AI agent the full API Builder workflow as a skill. The skill teaches the agent
				spec authoring, validation, code generation, compiler verification, and testing.
			</p>
			<p class="text-ab-dark-blue">
				<a href="https://github.com/mbryzek/apibuilder-ui/blob/main/skills/apibuilder.md" class="text-ab-blue hover:text-ab-dark-blue underline">
					View the skill on GitHub
				</a>
			</p>
		</div>
	</div>

	<!-- CTA -->
	<div class="mt-12 mb-8 text-center">
		<p class="text-ab-dark-blue mb-4">Explore the full API specification format.</p>
		<a href="/doc/apiJson" class="btn-primary inline-block">api.json Reference</a>
	</div>
</div>
